name: lorenzetti
services:
  lorenzetti:
    image: lorenzetti/lorenzetti:${TAG}
    container_name: lorenzetti-container
    volumes:
      - /home/${USERNAME}/data:/root/data
      - /mnt/d/data:/root/ext_data
      - /home/${USERNAME}/workspaces/lorenzetti:/root/workspaces/lorenzetti
      - /home/${USERNAME}/logs:/root/logs
    tty: true
    environment:
    - LZT_DATA=${LZT_DATA}
    - PYTHONPATH=${PYTHONPATH}
    - LZT_REPO=${LZT_REPO}
