name: lorenzetti-${TAG}
services:
  lorenzetti:
    image: ${DOCKER_USERNAME}/lorenzetti:${TAG}
    container_name: lzt-container-${TAG}
    volumes:
      - /home/${USERNAME}/data:/root/data
      - /mnt/d/data:/root/ext_data
      - /home/${USERNAME}/workspaces/lorenzetti:/root/workspaces/lorenzetti
      - /home/${USERNAME}/logs:/root/logs
    tty: true
    environment:
    - LZT_DATA=${LZT_DATA}
    - LZT_REPO=${LZT_REPO}
    # - PYTHONPATH=${PYTHONPATH}
