[project]
name = "boosted-lorenzetti"
version = "0.1.0"
description = "Repository for boosted analysis with Lorenzetti Shower Simulator"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
