import ROOT
import logging
from pathlib import Path
import logging.config
from . import constants
from . import dataset
from . import formulas
from . import metrics
from . import norms
from . import root
from . import utils
from . import plotting

CPP_DIR = Path(__file__).parent / 'include' / 'Lorenzetti'
CPP_FILE_EXTENSIONS = [
    '*.h'
]
for file_ext in CPP_FILE_EXTENSIONS:
    for filename in CPP_DIR.glob(file_ext):
        logging.debug(f'Decalring header file {filename}')
        text = filename.read_text()
        ROOT.gInterpreter.Declare(text)

ESD_STRUCT_FILEDS = [
    'CaloCellContainer_Cells.descriptor_link',
    'CaloCellContainer_Cells.deta',
    'CaloCellContainer_Cells.dphi',
    'CaloCellContainer_Cells.e',
    'CaloCellContainer_Cells.et',
    'CaloCellContainer_Cells.eta',
    'CaloCellContainer_Cells.phi',
    'CaloCellContainer_Cells.tau',
    'CaloDetDescriptorContainer_Cells.bc_duration',
    'CaloDetDescriptorContainer_Cells.bcid_end',
    'CaloDetDescriptorContainer_Cells.bcid_start',
    'CaloDetDescriptorContainer_Cells.cell_link',
    'CaloDetDescriptorContainer_Cells.deta',
    'CaloDetDescriptorContainer_Cells.detector',
    'CaloDetDescriptorContainer_Cells.dphi',
    'CaloDetDescriptorContainer_Cells.e',
    'CaloDetDescriptorContainer_Cells.edep',
    'CaloDetDescriptorContainer_Cells.edep_per_bunch',
    'CaloDetDescriptorContainer_Cells.eta',
    'CaloDetDescriptorContainer_Cells.hash',
    'CaloDetDescriptorContainer_Cells.phi',
    'CaloDetDescriptorContainer_Cells.pulse',
    'CaloDetDescriptorContainer_Cells.sampling',
    'CaloDetDescriptorContainer_Cells.tau',
    'CaloDetDescriptorContainer_Cells.tof',
    'CaloDetDescriptorContainer_Cells.z',
    'EventInfoContainer_Events.avgmu',
    'EventInfoContainer_Events.eventNumber',
    'EventInfoContainer_Events.runNumber',
    'EventSeedContainer_Seeds.e',
    'EventSeedContainer_Seeds.et',
    'EventSeedContainer_Seeds.eta',
    'EventSeedContainer_Seeds.id',
    'EventSeedContainer_Seeds.phi',
    'TruthParticleContainer_Particles.e',
    'TruthParticleContainer_Particles.et',
    'TruthParticleContainer_Particles.eta',
    'TruthParticleContainer_Particles.pdgid',
    'TruthParticleContainer_Particles.phi',
    'TruthParticleContainer_Particles.px',
    'TruthParticleContainer_Particles.py',
    'TruthParticleContainer_Particles.pz',
    'TruthParticleContainer_Particles.seedid',
    'TruthParticleContainer_Particles.vx',
    'TruthParticleContainer_Particles.vy',
    'TruthParticleContainer_Particles.vz'
]


AOD_STRUCT_FIELDS = [
    'CaloCellContainer_Cells.descriptor_link',
    'CaloCellContainer_Cells.deta',
    'CaloCellContainer_Cells.dphi',
    'CaloCellContainer_Cells.e',
    'CaloCellContainer_Cells.et',
    'CaloCellContainer_Cells.eta',
    'CaloCellContainer_Cells.phi',
    'CaloCellContainer_Cells.tau',
    'CaloClusterContainer_Clusters.cell_links',
    'CaloClusterContainer_Clusters.deta',
    'CaloClusterContainer_Clusters.dphi',
    'CaloClusterContainer_Clusters.e',
    'CaloClusterContainer_Clusters.e0',
    'CaloClusterContainer_Clusters.e1',
    'CaloClusterContainer_Clusters.e2',
    'CaloClusterContainer_Clusters.e233',
    'CaloClusterContainer_Clusters.e237',
    'CaloClusterContainer_Clusters.e277',
    'CaloClusterContainer_Clusters.e2tsts1',
    'CaloClusterContainer_Clusters.e3',
    'CaloClusterContainer_Clusters.ehad1',
    'CaloClusterContainer_Clusters.ehad2',
    'CaloClusterContainer_Clusters.ehad3',
    'CaloClusterContainer_Clusters.emaxs1',
    'CaloClusterContainer_Clusters.emaxs2',
    'CaloClusterContainer_Clusters.eratio',
    'CaloClusterContainer_Clusters.et',
    'CaloClusterContainer_Clusters.eta',
    'CaloClusterContainer_Clusters.etot',
    'CaloClusterContainer_Clusters.f0',
    'CaloClusterContainer_Clusters.f1',
    'CaloClusterContainer_Clusters.f2',
    'CaloClusterContainer_Clusters.f3',
    'CaloClusterContainer_Clusters.fracMax',
    'CaloClusterContainer_Clusters.lambdaCenter',
    'CaloClusterContainer_Clusters.lateralMom',
    'CaloClusterContainer_Clusters.longitudinalMom',
    'CaloClusterContainer_Clusters.phi',
    'CaloClusterContainer_Clusters.reta',
    'CaloClusterContainer_Clusters.rhad',
    'CaloClusterContainer_Clusters.rhad1',
    'CaloClusterContainer_Clusters.rphi',
    'CaloClusterContainer_Clusters.secondLambda',
    'CaloClusterContainer_Clusters.secondR',
    'CaloClusterContainer_Clusters.weta2',
    'CaloDetDescriptorContainer_Cells.bc_duration',
    'CaloDetDescriptorContainer_Cells.bcid_end',
    'CaloDetDescriptorContainer_Cells.bcid_start',
    'CaloDetDescriptorContainer_Cells.cell_link',
    'CaloDetDescriptorContainer_Cells.deta',
    'CaloDetDescriptorContainer_Cells.detector',
    'CaloDetDescriptorContainer_Cells.dphi',
    'CaloDetDescriptorContainer_Cells.e',
    'CaloDetDescriptorContainer_Cells.edep',
    'CaloDetDescriptorContainer_Cells.edep_per_bunch',
    'CaloDetDescriptorContainer_Cells.eta',
    'CaloDetDescriptorContainer_Cells.hash',
    'CaloDetDescriptorContainer_Cells.phi',
    'CaloDetDescriptorContainer_Cells.pulse',
    'CaloDetDescriptorContainer_Cells.sampling',
    'CaloDetDescriptorContainer_Cells.tau',
    'CaloDetDescriptorContainer_Cells.tof',
    'CaloDetDescriptorContainer_Cells.z',
    'CaloRingsContainer_Rings.cluster_link',
    'CaloRingsContainer_Rings.rings',
    'ElectronContainer_Electrons.cluster_link',
    'ElectronContainer_Electrons.decisions',
    'ElectronContainer_Electrons.e',
    'ElectronContainer_Electrons.et',
    'ElectronContainer_Electrons.eta',
    'ElectronContainer_Electrons.phi',
    'EventInfoContainer_Events.avgmu',
    'EventInfoContainer_Events.eventNumber',
    'EventInfoContainer_Events.runNumber',
    'EventSeedContainer_Seeds.e',
    'EventSeedContainer_Seeds.et',
    'EventSeedContainer_Seeds.eta',
    'EventSeedContainer_Seeds.id',
    'EventSeedContainer_Seeds.phi',
    'TruthParticleContainer_Particles.e',
    'TruthParticleContainer_Particles.et',
    'TruthParticleContainer_Particles.eta',
    'TruthParticleContainer_Particles.pdgid',
    'TruthParticleContainer_Particles.phi',
    'TruthParticleContainer_Particles.px',
    'TruthParticleContainer_Particles.py',
    'TruthParticleContainer_Particles.pz',
    'TruthParticleContainer_Particles.seedid',
    'TruthParticleContainer_Particles.vx',
    'TruthParticleContainer_Particles.vy',
    'TruthParticleContainer_Particles.vz'
]

logging_config = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s | %(levelname)s | %(name)s | %(module)s"
            " | %(lineno)s | %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S"
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "default",
            "stream": "ext://sys.stdout"
        },
    },
    "loggers": {
        "": {
            "level": "DEBUG",
            "handlers": ["stdout"]
        }
    }
}
logging.config.dictConfig(logging_config)

# LZT_UTILS_INCLUDE_PATHS = [
#     "/root/workspaces/lorenzetti/boosted-lorenzetti/lzt_utils/include"
# ]

# INCLUDE_PATHS = LZT_UTILS_INCLUDE_PATHS + [
#     "/root/workspaces/lorenzetti/lorenzetti/events/EventInfo",
#     "/root/workspaces/lorenzetti/lorenzetti/events/TruthParticle",
#     "/root/workspaces/lorenzetti/lorenzetti/events/CaloCell",
#     "/root/workspaces/lorenzetti/lorenzetti/core/GaugiKernel",
#     "/physics/pythia8/include",
#     "/physics/fastjet-3.3.3/include",
#     "/physics/hepmc/hepmc3/include",
#     "/physics/geant/geant4/source/tracking/include",
#     "/physics/geant/geant4/source/physics_lists/util/include",
#     "/physics/geant/geant4/source/physics_lists/lists/include",
#     "/physics/geant/geant4/source/physics_lists/builders/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/limiters/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/decay/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/gamma_lepto_nuclear/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/electromagnetic/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/factory/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/hadron_elastic/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/hadron_inelastic/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/ions/include",
#     "/physics/geant/geant4/source/physics_lists/constructors/stopping/include",
#     "/physics/geant/geant4/source/analysis/hntools/include",
#     "/physics/geant/geant4/source/analysis/csv/include",
#     "/physics/geant/geant4/source/analysis/management/include",
#     "/physics/geant/geant4/source/analysis/xml/include",
#     "/physics/geant/geant4/source/analysis/accumulables/include",
#     "/physics/geant/geant4/source/analysis/hdf5/include",
#     "/physics/geant/geant4/source/analysis/g4tools/include",
#     "/physics/geant/geant4/source/analysis/root/include",
#     "/physics/geant/geant4/source/g3tog4/include",
#     "/physics/geant/geant4/source/interfaces/common/include",
#     "/physics/geant/geant4/source/interfaces/GAG/include",
#     "/physics/geant/geant4/source/interfaces/basic/include",
#     "/physics/geant/geant4/source/intercoms/include",
#     "/physics/geant/geant4/source/error_propagation/include",
#     "/physics/geant/geant4/source/track/include",
#     "/physics/geant/geant4/source/event/include",
#     "/physics/geant/geant4/source/materials/include",
#     "/physics/geant/geant4/source/processes/parameterisation/include",
#     "/physics/geant/geant4/source/processes/scoring/include",
#     "/physics/geant/geant4/source/processes/management/include",
#     "/physics/geant/geant4/source/processes/decay/include",
#     "/physics/geant/geant4/source/processes/optical/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/highenergy/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/pii/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/lowenergy/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/muons/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/utils/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/xrays/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/dna/models/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/dna/management/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/dna/utils/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/dna/molecules/management/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/dna/molecules/types/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/dna/processes/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/polarisation/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/standard/include",
#     "/physics/geant/geant4/source/processes/electromagnetic/adjoint/include",
#     "/physics/geant/geant4/source/processes/hadronic/cross_sections/include",
#     "/physics/geant/geant4/source/processes/hadronic/util/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/gamma_nuclear/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/util/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/em_dissociation/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/particle_hp/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/lepto_nuclear/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/qmd/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/multifragmentation/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/util/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/photon_evaporation/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/fermi_breakup/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/gem_evaporation/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/management/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/evaporation/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/handler/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/fission/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/de_excitation/ablation/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/management/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/abrasion/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/inclxx/interface/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/inclxx/utils/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/inclxx/incl_physics/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/abla/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/lend/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/rpg/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/cascade/cascade/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/fission/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/theo_high_energy/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/pre_equilibrium/exciton_model/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/binary_cascade/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/parton_string/hadronization/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/parton_string/management/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/parton_string/diffraction/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/parton_string/qgsm/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/radioactive_decay/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/im_r_matrix/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/coherent_elastic/include",
#     "/physics/geant/geant4/source/processes/hadronic/models/quasi_elastic/include",
#     "/physics/geant/geant4/source/processes/hadronic/management/include",
#     "/physics/geant/geant4/source/processes/hadronic/processes/include",
#     "/physics/geant/geant4/source/processes/hadronic/stopping/include",
#     "/physics/geant/geant4/source/processes/transportation/include",
#     "/physics/geant/geant4/source/processes/cuts/include",
#     "/physics/geant/geant4/source/processes/biasing/importance/include",
#     "/physics/geant/geant4/source/processes/biasing/management/include",
#     "/physics/geant/geant4/source/processes/biasing/generic/include",
#     "/physics/geant/geant4/source/processes/solidstate/channeling/include",
#     "/physics/geant/geant4/source/processes/solidstate/phonon/include",
#     "/physics/geant/geant4/source/graphics_reps/include",
#     "/physics/geant/geant4/source/persistency/gdml/include",
#     "/physics/geant/geant4/source/persistency/mctruth/include",
#     "/physics/geant/geant4/source/persistency/ascii/include",
#     "/physics/geant/geant4/source/readout/include",
#     "/physics/geant/geant4/source/run/include",
#     "/physics/geant/geant4/source/particles/management/include",
#     "/physics/geant/geant4/source/particles/leptons/include",
#     "/physics/geant/geant4/source/particles/utils/include",
#     "/physics/geant/geant4/source/particles/shortlived/include",
#     "/physics/geant/geant4/source/particles/bosons/include",
#     "/physics/geant/geant4/source/particles/hadrons/mesons/include",
#     "/physics/geant/geant4/source/particles/hadrons/barions/include",
#     "/physics/geant/geant4/source/particles/hadrons/ions/include",
#     "/physics/geant/geant4/source/particles/adjoint/include",
#     "/physics/geant/geant4/source/global/HEPRandom/include",
#     "/physics/geant/geant4/source/global/management/include",
#     "/physics/geant/geant4/source/global/HEPNumerics/include",
#     "/physics/geant/geant4/source/global/HEPGeometry/include",
#     "/physics/geant/geant4/source/externals/expat/include",
#     "/physics/geant/geant4/source/externals/clhep/include",
#     "/physics/geant/geant4/source/externals/zlib/include",
#     "/physics/geant/geant4/source/geometry/magneticfield/include",
#     "/physics/geant/geant4/source/geometry/navigation/include",
#     "/physics/geant/geant4/source/geometry/volumes/include",
#     "/physics/geant/geant4/source/geometry/management/include",
#     "/physics/geant/geant4/source/geometry/biasing/include",
#     "/physics/geant/geant4/source/geometry/divisions/include",
#     "/physics/geant/geant4/source/geometry/solids/specific/include",
#     "/physics/geant/geant4/source/geometry/solids/Boolean/include",
#     "/physics/geant/geant4/source/geometry/solids/CSG/include",
#     "/physics/geant/geant4/source/parameterisations/gflash/include",
#     "/physics/geant/geant4/source/digits_hits/scorer/include",
#     "/physics/geant/geant4/source/digits_hits/utils/include",
#     "/physics/geant/geant4/source/digits_hits/digits/include",
#     "/physics/geant/geant4/source/digits_hits/detector/include",
#     "/physics/geant/geant4/source/digits_hits/hits/include",
#     "/physics/geant/geant4/source/visualization/OpenInventor/include",
#     "/physics/geant/geant4/source/visualization/RayTracer/include",
#     "/physics/geant/geant4/source/visualization/management/include",
#     "/physics/geant/geant4/source/visualization/gMocren/include",
#     "/physics/geant/geant4/source/visualization/VRML/include",
#     "/physics/geant/geant4/source/visualization/modeling/include",
#     "/physics/geant/geant4/source/visualization/HepRep/include",
#     "/physics/geant/geant4/source/visualization/XXX/include",
#     "/physics/geant/geant4/source/visualization/externals/gl2ps/include",
#     "/physics/geant/geant4/source/visualization/OpenGL/include",
#     "/physics/geant/geant4/source/visualization/FukuiRenderer/include",
#     "/physics/geant/geant4/source/visualization/Tree/include"
# ]
